BED=/seq/schatz/mnattest/Assemblytics/Alu_tests/Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.bed

# Use tail because bed file has a header
sort -k1,1 -k2,2n <(tail -n +2 $BED) > "${BED%.bed}".sorted.bed

cat Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.bed | grep "Deletion" | awk '$5>=300 && $5<=350' > Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.Deletions_300-350bp.bed
cat Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.bed | grep "Insertion" | awk '$5>=300 && $5<=350' > Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.Insertions_300-350bp.bed


FEATURES=/seq/schatz/SKBR3/repeat_analysis/repeat_masker.hg19.sorted.bed


# Total deletions:
cat Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.Deletions_300-350bp.bed | cut -f 4 | sort | uniq | wc -l
cat $FEATURES | grep -i Alu > Repeat_Masker.Alu_elements.bed

bedtools intersect -a Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.Deletions_300-350bp.bed -b Repeat_Masker.Alu_elements.bed -sorted | cut -f 4 | sort | uniq | wc -l



# Total insertions:
cat Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.Insertions_300-350bp.bed | cut -f 4 | sort | uniq | wc -l

cat Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.Insertions_300-350bp.bed | cut -f 10 | sed 's/..$//' > Homo_sapiens_MHAP_assembly.Assemblytics_structural_variants.sorted.Insertions_300-350bp.bed.query_coordinates

# From here we run extract_insertions.script to fill the putative_Alu_sequences directory with tiny fasta files of sequences
qsub extract_insertions.script

# Now combine all these together in one file
cat putative_Alu_sequences/*.fa > all_putative_Alu_insertions.fa

# Then we can Blast all these sequences against the "Human ALU repeat elements" database
# Download the Hit_Table.csv

cat ~/Downloads/EGWPAFJ6013-Alignment-HitTable.csv | tr "," "\t" | cut -f 1 | sort | uniq | wc -l
#  548 count
